// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkmvcojvecmlqtjtpdqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrbXZjb2p2ZWNtbHF0anRwZHFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDE3MTQsImV4cCI6MjA1OTY3NzcxNH0.TsYzjx0173MlF51W6EzkXmmZDIv9yOfHK2stcLM9HOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);